import { expect, test } from "@playwright/test"

const groupSelector = '[data-slot="thread-process-group"]'

test("only consecutive process items collapse; input, Activity and assistant replies stay visible", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto("/e2e/thread-history.html")
  const groups = page.locator(groupSelector)
  await expect(groups).toHaveCount(3)
  for (const group of await groups.all()) await expect(group).not.toHaveAttribute("open")
  await expect(page.getByText("请检查部署状态。", { exact: true })).toBeVisible()
  await expect(page.getByText("Activity：已完成第一阶段检查。", { exact: true })).toBeVisible()
  await expect(page.getByText("AI 回复：部署检查通过，正在检查服务。", { exact: true })).toBeVisible()
  await expect(page.getByText("正在分析部署记录。", { exact: true })).toBeHidden()
  await expect(page.getByText("已保存上下文检查点。", { exact: true })).toBeHidden()
  await expect(groups.first().locator(":scope > summary")).toContainText("3 条")
  await expect(groups.first().locator(":scope > summary")).toContainText("运行了 01 小时 01 分钟 05 秒")
  await expect(groups.nth(1).locator(":scope > summary")).toContainText("1 条")
  await expect(groups.nth(1).locator(":scope > summary")).toContainText("运行了 00 小时 00 分钟 00 秒")
  await groups.first().locator(":scope > summary").click()
  await expect(page.getByText("正在分析部署记录。", { exact: true })).toBeVisible()
  await expect(page.getByText("部署检查通过。", { exact: true })).toBeVisible()
  expect(await groups.first().locator("article").evaluateAll((rows) => rows.map((row) => row.getAttribute("data-record-id")))).toEqual(["2", "3", "4"])
  await groups.first().getByText("原始记录 #2", { exact: true }).click()
  await expect(groups.first().locator("pre").first()).toBeVisible()
  await expect(groups.nth(1)).not.toHaveAttribute("open")
  expect(errors).toEqual([])
})

test("keyboard toggles, polling, language changes and streaming handoff preserve local disclosure state", async ({ page }) => {
  await page.goto("/e2e/thread-history.html")
  const groups = page.locator(groupSelector)
  const last = groups.last()
  const summary = last.locator(":scope > summary")
  await summary.focus()
  await page.keyboard.press("Enter")
  await expect(last).toHaveAttribute("open", "")
  await expect(last.getByText("正在检查服务健康状态。", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Poll", exact: true }).click()
  await expect(last).toHaveAttribute("open", "")
  await page.getByRole("button", { name: "Language", exact: true }).click()
  await expect(summary).toContainText("1 message")
  await expect(summary).toContainText("Ran for 00h 00m 00s")
  await expect(last).toHaveAttribute("open", "")
  await page.getByRole("button", { name: "Append", exact: true }).click()
  await expect(groups).toHaveCount(3)
  await expect(last).toHaveAttribute("open", "")
  await expect(summary).toContainText("2 messages")
  await expect(summary).toContainText("Ran for 00h 02m 15s")
  await expect(last.locator("article")).toHaveCount(2)
  await expect(last.locator('[data-record-id="8"]')).toHaveCount(1)
  await expect(last.locator('[data-record-id="-1"]')).toHaveCount(0)
  await page.getByRole("button", { name: "Finish", exact: true }).click()
  await expect(last).toHaveAttribute("open", "")
  await expect(page.getByText("AI 回复：全部检查通过。", { exact: true })).toBeVisible()
  await expect(summary).toContainText("Ran for 00h 02m 15s")
  await summary.focus()
  await page.keyboard.press("Space")
  await expect(last).not.toHaveAttribute("open")
  await page.keyboard.press("Enter")
  await expect(last).toHaveAttribute("open", "")
  await page.getByRole("button", { name: "Thread", exact: true }).click()
  await expect(groups.last()).not.toHaveAttribute("open")
  await groups.last().locator(":scope > summary").click()
  await page.reload()
  await expect(page.locator(groupSelector).last()).not.toHaveAttribute("open")
})

test("compact and expanded groups wrap on narrow screens in both themes and languages", async ({ page }) => {
  await page.goto("/e2e/thread-history.html")
  for (const theme of ["light", "dark"]) {
    if (theme === "dark") await page.getByRole("button", { name: "Theme", exact: true }).click()
    for (const language of ["zh", "en"]) {
      if (language === "en") await page.getByRole("button", { name: "Language", exact: true }).click()
      for (const width of [1280, 390, 320]) {
        await page.setViewportSize({ width, height: 844 })
        const group = page.locator(groupSelector).first()
        await group.scrollIntoViewIfNeeded()
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
        expect(await page.locator('[data-slot="message-scroller-viewport"]').evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
        await page.screenshot({ path: `test-results/thread-history-${theme}-${language}-${width}.png`, fullPage: true })
        await group.locator(":scope > summary").click()
        await expect(group).toHaveAttribute("open", "")
        expect(await page.locator('[data-slot="message-scroller-viewport"]').evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true)
        await group.locator(":scope > summary").click()
      }
    }
    await page.getByRole("button", { name: "Language", exact: true }).click()
  }
})
