import { expect, test } from "@playwright/test"

test("the popover groups models by upstream and edits reasoning effort and fast mode", async ({ page }) => {
  await page.goto("/e2e/thread-settings.html")
  const trigger = page.getByRole("button", { name: "线程设置" })
  await expect(trigger).toHaveText("deepseek-flash (medium)")
  await trigger.click()
  const popover = page.locator('[data-slot="popover-content"]')
  await expect(popover).toBeVisible()
  await expect(popover.getByText("推理强度")).toBeVisible()
  const scale = popover.locator('[data-slot="reasoning-effort-scale"]')
  for (const stop of ["low", "medium", "high", "xhigh", "max"]) await expect(scale.getByText(stop, { exact: true })).toBeVisible()
  const effortValue = popover.locator('[data-slot="reasoning-effort-value"]')
  await expect(effortValue).toHaveText("medium")
  await popover.getByRole("combobox").click()
  await expect(page.getByText("DeepSeek", { exact: true })).toBeVisible()
  await expect(page.getByText("OpenAI-LB", { exact: true })).toBeVisible()
  await expect(page.getByText("Could not load models")).toBeVisible()
  await page.getByRole("option", { name: "gpt-6-astra" }).click()
  await expect(page.getByTestId("selection")).toHaveText("up-deepseek:gpt-6-astra")
  await expect(trigger).toHaveText("gpt-6-astra (medium)")
  await popover.getByRole("combobox").click()
  await page.getByRole("option", { name: "meta-llama/Llama-3.1-8B-Instruct" }).click()
  await expect(page.getByTestId("selection")).toHaveText("up-lb:meta-llama/Llama-3.1-8B-Instruct")
  await expect(trigger).toHaveText("meta-llama/Llama-3.1-8B-Instruct (medium)")
  const slider = popover.getByRole("slider")
  await slider.press("End")
  await expect(page.getByTestId("effort")).toHaveText("max")
  await expect(effortValue).toHaveText("max")
  await expect(trigger).toHaveText("meta-llama/Llama-3.1-8B-Instruct (max)")
  await slider.press("ArrowLeft")
  await expect(page.getByTestId("effort")).toHaveText("xhigh")
  await expect(effortValue).toHaveText("xhigh")
  await expect(trigger).toHaveText("meta-llama/Llama-3.1-8B-Instruct (xhigh)")
  await popover.getByRole("switch").click()
  await expect(page.getByTestId("fast")).toHaveText("true")
  const budget = popover.getByLabel("上下文预算")
  await expect(budget).toHaveAttribute("placeholder", "200000")
  await budget.fill("150000")
  await expect(page.getByTestId("budget")).toHaveText("150000")
  await budget.fill("")
  await expect(page.getByTestId("budget")).toHaveText("null")
  await page.keyboard.press("Escape")
  await expect(popover).toBeHidden()
})

test("the popover follows the language and stays within narrow layouts", async ({ page }) => {
  await page.goto("/e2e/thread-settings.html")
  await page.setViewportSize({ width: 390, height: 844 })
  for (const language of ["zh", "en"]) {
    if (language === "en") await page.getByRole("button", { name: "Language", exact: true }).click()
    for (const dark of [false, true]) {
      await page.evaluate((value) => document.documentElement.classList.toggle("dark", value), dark)
      await page.getByRole("button", { name: language === "en" ? "Thread settings" : "线程设置" }).click()
      const popover = page.locator('[data-slot="popover-content"]')
      await expect(popover).toBeVisible()
      await expect(popover).toContainText(language === "en" ? "Reasoning effort" : "推理强度")
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      await page.keyboard.press("Escape")
      await expect(popover).toBeHidden()
    }
  }
  await page.screenshot({ path: "test-results/thread-settings-mobile.png" })
})

test("a long selection truncates inside the composer row on narrow layouts", async ({ page }) => {
  await page.goto("/e2e/thread-settings.html")
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("button", { name: "线程设置" }).click()
  const popover = page.locator('[data-slot="popover-content"]')
  await popover.getByRole("combobox").click()
  await page.getByRole("option", { name: "meta-llama/Llama-3.1-8B-Instruct" }).click()
  await page.keyboard.press("Escape")
  await expect(popover).toBeHidden()
  const trigger = page.getByRole("button", { name: "线程设置" })
  await expect(trigger).toHaveText("meta-llama/Llama-3.1-8B-Instruct (medium)")
  await expect(page.getByRole("button", { name: "发送" })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const spans = await trigger.evaluate((element) => {
    const [model, effort] = element.querySelectorAll("span")
    return { model: model.scrollWidth > model.clientWidth, effort: effort.scrollWidth > effort.clientWidth }
  })
  expect(spans).toEqual({ model: true, effort: false })
  const box = await trigger.boundingBox()
  expect(box !== null && box.x >= 0 && box.x + box.width <= 390).toBe(true)
  await page.screenshot({ path: "test-results/thread-settings-long-model.png" })
})
