import { QueryClient, QueryClientProvider, useQuery, useQueryClient } from '@tanstack/react-query'
import { createBrowserSdk } from 'auth-mini/sdk/browser'
import type { AuthMiniApi, SessionSnapshot } from 'auth-mini/sdk/browser'
import { ActivityIcon, BotIcon, CheckIcon, CircleStopIcon, DatabaseIcon, FileIcon, FolderIcon, HardDriveIcon, KeyRoundIcon, LoaderCircleIcon, MonitorCogIcon, NetworkIcon, PanelLeftIcon, PlusIcon, RefreshCwIcon, SendIcon, ServerIcon, Settings2Icon, TerminalSquareIcon, XIcon } from 'lucide-react'
import { createContext, FormEvent, ReactNode, useContext, useEffect, useRef, useState } from 'react'
import { HashRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { createRoot } from 'react-dom/client'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupTextarea } from '@/components/ui/input-group'
import { Message, MessageAvatar, MessageContent, MessageHeader } from '@/components/ui/message'
import { MessageScroller, MessageScrollerButton, MessageScrollerContent, MessageScrollerItem, MessageScrollerProvider, MessageScrollerViewport } from '@/components/ui/message-scroller'
import { Separator } from '@/components/ui/separator'
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { Spinner } from '@/components/ui/spinner'
import { Textarea } from '@/components/ui/textarea'
import { TooltipProvider } from '@/components/ui/tooltip'
import './styles.css'

declare global { interface Window { __MOBIUS_AUTH_URL: string | null } }

type Status = { machine_id: string; hostname: string; root_user_id: string; auth_url: string; openai_base_url: string }
type Settings = { default_model: string }
type Peer = { id: string; name: string; base_url: string; created_at: string }
type FileEntry = { name: string; path: string; kind: 'file' | 'directory'; size: number }
type ChatMessage = { role: string; content: string | null }
type AgentEvent = { type: 'tool_call'; call_id: string; name: string } | { type: 'tool_result'; call_id: string; name: string } | { type: 'context'; input_tokens: number } | { type: 'complete'; message: ChatMessage } | { type: 'error'; error: string }
type ConversationItem = { kind: 'message'; id: string; message: ChatMessage; queued: boolean } | { kind: 'tool'; call_id: string; name: string; complete: boolean }
type Session = SessionSnapshot

const queryClient = new QueryClient()
const UiContext = createContext<{ dark: boolean; toggleTheme: () => void } | null>(null)

function UiProvider({ children }: { children: ReactNode }) {
  const [dark, setDark] = useState(() => localStorage.getItem('mobius.theme') === 'dark' || (!localStorage.getItem('mobius.theme') && matchMedia('(prefers-color-scheme: dark)').matches))
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('mobius.theme', dark ? 'dark' : 'light') }, [dark])
  return <UiContext.Provider value={{ dark, toggleTheme: () => setDark((value) => !value) }}>{children}</UiContext.Provider>
}

function useUi() { const value = useContext(UiContext); if (!value) throw new Error('UI context is missing'); return value }
function anonymous(): Session { return { status: 'anonymous', authenticated: false, sessionId: null, accessToken: null, refreshToken: null, receivedAt: null, expiresAt: null } }
function useBrowserSession(sdk: AuthMiniApi | null) { const [session, setSession] = useState<Session>(() => sdk?.session.getState() ?? anonymous()); useEffect(() => { if (!sdk) return; setSession(sdk.session.getState()); return sdk.session.onChange(setSession) }, [sdk]); return session }
function message(cause: unknown) { return cause instanceof Error ? cause.message : 'Something went wrong.' }
function bytes(value: number) { const units = ['B', 'KB', 'MB', 'GB', 'TB']; let size = value; let index = 0; while (size >= 1024 && index < units.length - 1) { size /= 1024; index++ } return `${size >= 10 || index === 0 ? size.toFixed(0) : size.toFixed(1)} ${units[index]}` }

async function api<T>(path: string, token: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...init?.headers } })
  if (!response.ok) { const body = await response.json().catch(() => ({ error: response.statusText })); throw new Error(body.error ?? response.statusText) }
  return response.json() as Promise<T>
}

async function streamAgentTurn(token: string, runId: string, messages: ChatMessage[], signal: AbortSignal, onEvent: (event: AgentEvent) => void) {
  const response = await fetch('/api/agent/turn', { method: 'POST', signal, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ run_id: runId, messages }) })
  if (!response.ok) { const body = await response.json().catch(() => ({ error: response.statusText })); throw new Error(body.error ?? response.statusText) }
  const reader = response.body?.getReader(); if (!reader) throw new Error('The agent did not start an event stream.')
  const decoder = new TextDecoder(); let buffer = ''
  for (;;) { const { done, value } = await reader.read(); if (done) return; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop() ?? ''; for (const line of lines) { if (!line.startsWith('data: ')) continue; const event = JSON.parse(line.slice(6)) as AgentEvent; onEvent(event); if (event.type === 'error') throw new Error(event.error) } }
}

function normalizedAuthUrl(authUrl: string) { const url = new URL(authUrl.trim()); url.search = ''; url.hash = ''; url.pathname = url.pathname.endsWith('/') ? url.pathname : `${url.pathname}/`; return url.toString() }
function beginAuthRedirect(authUrl: string) { const normalized = normalizedAuthUrl(authUrl); const state = crypto.randomUUID(); sessionStorage.setItem('mobius.auth_url', normalized); sessionStorage.setItem('mobius.login_state', state); const callback = `${location.origin}${location.pathname}#/auth/callback`; const params = new URLSearchParams({ redirect_uri: callback, state }); if (location.protocol === 'http:' && ['localhost', '127.0.0.1', '[::1]'].includes(location.hostname)) params.set('aud', location.hostname); location.assign(`${normalized}web/#/login?${params.toString()}`) }
function acceptRedirectSession(): string | null { if (!location.hash.startsWith('#/auth/callback?')) return null; const params = new URLSearchParams(location.hash.slice('#/auth/callback?'.length)); const state = sessionStorage.getItem('mobius.login_state'); const authUrl = sessionStorage.getItem('mobius.auth_url'); if (!authUrl || !state || params.get('state') !== state) return null; const accessToken = params.get('access_token'); const sessionId = params.get('session_id'); const refreshToken = params.get('refresh_token'); const expiresIn = Number(params.get('expires_in')); if (!accessToken || !sessionId || !refreshToken || !Number.isFinite(expiresIn)) return null; const receivedAt = new Date(); localStorage.setItem(`auth-mini.sdk:${normalizedAuthUrl(authUrl)}`, JSON.stringify({ accessToken, sessionId, refreshToken, receivedAt: receivedAt.toISOString(), expiresAt: new Date(receivedAt.getTime() + expiresIn * 1000).toISOString() })); sessionStorage.removeItem('mobius.login_state'); history.replaceState(null, '', `${location.pathname}${location.search}#/console`); return authUrl }

function App() { const authUrl = acceptRedirectSession() ?? window.__MOBIUS_AUTH_URL; const [sdk] = useState<AuthMiniApi | null>(() => authUrl ? createBrowserSdk(authUrl) : null); const session = useBrowserSession(sdk); if (!authUrl) return <Bootstrap session={session} />; if (session.status === 'recovering') return <main className="grid min-h-svh place-items-center"><Spinner /></main>; if (!session.accessToken) return <SignIn />; return <Workspace sdk={sdk} token={session.accessToken} /> }

function Bootstrap({ session }: { session: Session }) { const [authUrl, setAuthUrl] = useState(() => sessionStorage.getItem('mobius.auth_url') ?? ''); const [apiKey, setApiKey] = useState(''); const [baseUrl, setBaseUrl] = useState('https://api.openai.com/v1'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const signIn = () => { try { beginAuthRedirect(authUrl) } catch (cause) { setError(message(cause)) } }; const setup = async (event: FormEvent) => { event.preventDefault(); if (!session.accessToken) return; setBusy(true); try { await api('/api/setup', session.accessToken, { method: 'POST', body: JSON.stringify({ auth_url: authUrl, openai_api_key: apiKey, openai_base_url: baseUrl }) }); location.reload() } catch (cause) { setError(message(cause)) } finally { setBusy(false) } }; return <main className="grid min-h-svh place-items-center p-6"><Card className="w-full max-w-lg"><CardHeader><CardTitle>Initialize Mobius</CardTitle><CardDescription>Bind this machine to your Auth Mini identity and OpenAI-compatible upstream.</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-6" onSubmit={setup}><FieldGroup><Field><FieldLabel htmlFor="auth-url">Auth Mini URL</FieldLabel><Input id="auth-url" value={authUrl} onChange={(event) => setAuthUrl(event.target.value)} required /></Field><Button type="button" variant="secondary" onClick={signIn}><KeyRoundIcon data-icon="inline-start" />Continue with Auth Mini</Button><Field><FieldLabel htmlFor="api-key">OpenAI API key</FieldLabel><Input id="api-key" type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} required /></Field><Field><FieldLabel htmlFor="base-url">Base URL</FieldLabel><Input id="base-url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field></FieldGroup>{error && <ErrorAlert error={error} />}<Button disabled={busy || !session.authenticated}>{busy && <Spinner data-icon="inline-start" />}Initialize</Button></form></CardContent></Card></main> }
function SignIn() { const [error, setError] = useState(''); return <main className="grid min-h-svh place-items-center p-6"><Card className="w-full max-w-sm"><CardHeader><CardTitle>Return to the machine</CardTitle><CardDescription>Sign in through the configured Auth Mini server.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{error && <ErrorAlert error={error} />}<Button onClick={() => { try { beginAuthRedirect(window.__MOBIUS_AUTH_URL!) } catch (cause) { setError(message(cause)) } }}>Continue with Auth Mini</Button></CardContent></Card></main> }

function Workspace({ sdk, token }: { sdk: AuthMiniApi | null; token: string }) { const navigate = useNavigate(); const { dark, toggleTheme } = useUi(); const status = useQuery({ queryKey: ['status'], queryFn: () => api<Status>('/api/status', token) }); const nav = [{ to: '/console', label: 'Console', icon: TerminalSquareIcon }, { to: '/machines', label: 'Machines', icon: NetworkIcon }, { to: '/files', label: 'Files', icon: FileIcon }, { to: '/resources', label: 'Resources', icon: ActivityIcon }, { to: '/settings', label: 'Settings', icon: Settings2Icon }]; return <SidebarProvider><Sidebar><SidebarHeader><div className="flex items-center gap-2 px-2 py-1 font-heading text-lg font-semibold"><TerminalSquareIcon />Mobius</div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Machine</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav.map(({ to, label, icon: Icon }) => <SidebarMenuItem key={to}><SidebarMenuButton asChild tooltip={label}><NavLink to={to} className={({ isActive }) => isActive ? 'font-medium' : ''}><Icon /><span>{label}</span></NavLink></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter><div className="flex items-center gap-2 px-2 text-xs text-muted-foreground"><ServerIcon />{status.data?.hostname ?? 'Connecting…'}</div><Button variant="ghost" size="sm" onClick={toggleTheme}><MonitorCogIcon data-icon="inline-start" />{dark ? 'Light' : 'Dark'}</Button><Button variant="ghost" size="sm" onClick={async () => { await sdk?.session.logout(); navigate('/console') }}>Sign out</Button></SidebarFooter></Sidebar><SidebarInset><header className="flex h-14 items-center gap-3 border-b px-4"><SidebarTrigger><PanelLeftIcon /></SidebarTrigger><Separator orientation="vertical" className="h-4" /><div className="min-w-0"><p className="truncate text-sm font-medium">{status.data?.hostname ?? 'Loading machine'}</p></div><Badge className="ml-auto" variant="secondary">Online</Badge></header><Routes><Route path="/console" element={<Console token={token} />} /><Route path="/machines" element={<Machines token={token} />} /><Route path="/files" element={<FilesPage token={token} />} /><Route path="/resources" element={<ResourcesPage token={token} />} /><Route path="/settings" element={<SettingsPage token={token} />} /><Route path="*" element={<Navigate to="/console" replace />} /></Routes></SidebarInset></SidebarProvider> }

function Console({ token }: { token: string }) {
  const initial = { kind: 'message', id: crypto.randomUUID(), message: { role: 'assistant', content: 'I am connected to this machine. Tell me the outcome you want to reach.' }, queued: false } as ConversationItem
  const [conversation, setConversation] = useState<ConversationItem[]>([initial]); const conversationRef = useRef(conversation); const queueRef = useRef<{ id: string; message: ChatMessage }[]>([]); const activeRef = useRef<{ id: string; controller: AbortController } | null>(null)
  const [draft, setDraft] = useState(''); const [activeRun, setActiveRun] = useState<string | null>(null); const [contextTokens, setContextTokens] = useState<number | null>(null); const [error, setError] = useState('')
  const updateConversation = (next: ConversationItem[]) => { conversationRef.current = next; setConversation(next) }
  const drain = async (): Promise<void> => { if (activeRef.current || queueRef.current.length === 0) return; const next = queueRef.current.shift()!; updateConversation(conversationRef.current.map((item) => item.kind === 'message' && item.id === next.id ? { ...item, queued: false } : item)); const runId = crypto.randomUUID(); const controller = new AbortController(); activeRef.current = { id: runId, controller }; setActiveRun(runId); setError(''); const messages = conversationRef.current.filter((item): item is Extract<ConversationItem, { kind: 'message' }> => item.kind === 'message' && !item.queued).map((item) => item.message); try { await streamAgentTurn(token, runId, messages, controller.signal, (event) => { if (event.type === 'tool_call') updateConversation([...conversationRef.current, { kind: 'tool', call_id: event.call_id, name: event.name, complete: false }]); if (event.type === 'tool_result') updateConversation(conversationRef.current.map((item) => item.kind === 'tool' && item.call_id === event.call_id ? { ...item, complete: true } : item)); if (event.type === 'context') setContextTokens(event.input_tokens); if (event.type === 'complete') updateConversation([...conversationRef.current, { kind: 'message', id: crypto.randomUUID(), message: event.message, queued: false }]) }) } catch (cause) { if (!controller.signal.aborted) setError(message(cause)) } finally { activeRef.current = null; setActiveRun(null); void drain() } }
  const submit = (event: FormEvent) => { event.preventDefault(); const content = draft.trim(); if (!content) return; const queued = activeRef.current !== null || queueRef.current.length > 0; const entry: Extract<ConversationItem, { kind: 'message' }> = { kind: 'message', id: crypto.randomUUID(), message: { role: 'user', content }, queued }; updateConversation([...conversationRef.current, entry]); queueRef.current.push({ id: entry.id, message: entry.message }); setDraft(''); void drain() }
  const stop = async () => { const active = activeRef.current; if (!active) return; queueRef.current = []; updateConversation(conversationRef.current.filter((item) => item.kind !== 'message' || !item.queued)); active.controller.abort(); await api(`/api/agent/turn/${active.id}`, token, { method: 'DELETE' }).catch(() => undefined) }
  return <main className="flex h-[calc(100svh-3.5rem)] flex-col"><div className="flex flex-wrap items-center gap-2 border-b px-4 py-3"><div><h1 className="font-heading text-lg font-semibold">Console</h1><p className="text-sm text-muted-foreground">Agent activity is streamed as it happens.</p></div><Badge className="ml-auto" variant="outline">Context: {contextTokens?.toLocaleString() ?? '—'} tokens</Badge>{activeRun && <Button variant="destructive" size="sm" onClick={stop}><CircleStopIcon data-icon="inline-start" />Stop</Button>}</div><MessageScrollerProvider><MessageScroller className="flex-1"><MessageScrollerViewport><MessageScrollerContent className="mx-auto w-full max-w-4xl p-4">{conversation.map((item) => <MessageScrollerItem key={item.kind === 'tool' ? item.call_id : item.id} scrollAnchor><ConversationEntry item={item} /></MessageScrollerItem>)}{activeRun && <MessageScrollerItem scrollAnchor><div className="flex items-center gap-2 text-sm text-muted-foreground"><Spinner />Agent is working…</div></MessageScrollerItem>}</MessageScrollerContent></MessageScrollerViewport><MessageScrollerButton /></MessageScroller></MessageScrollerProvider>{error && <div className="px-4 pb-2"><ErrorAlert error={error} /></div>}<form className="border-t p-4" onSubmit={submit}><InputGroup className="mx-auto max-w-4xl"><InputGroupTextarea value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit() } }} placeholder={activeRun ? 'Add a follow-up prompt to the queue…' : 'Describe the outcome you want…'} rows={2} /><InputGroupAddon align="inline-end"><InputGroupButton type="submit" variant="default" size="icon-sm"><SendIcon /><span className="sr-only">Send</span></InputGroupButton></InputGroupAddon></InputGroup><p className="mx-auto mt-2 max-w-4xl text-xs text-muted-foreground">Enter to send · Shift+Enter for a new line{queueRef.current.length > 0 ? ` · ${queueRef.current.length} queued` : ''}</p></form></main>
}

function ConversationEntry({ item }: { item: ConversationItem }) { if (item.kind === 'tool') return <div className="flex items-center gap-2"><Badge variant={item.complete ? 'secondary' : 'outline'}>{item.complete ? <CheckIcon data-icon="inline-start" /> : <Spinner data-icon="inline-start" />}{item.complete ? 'Completed' : 'Calling'} {item.name}</Badge></div>; const assistant = item.message.role === 'assistant'; return <Message align={assistant ? 'start' : 'end'}><MessageAvatar>{assistant ? <BotIcon /> : 'You'}</MessageAvatar><MessageContent><MessageHeader>{assistant ? 'Agent' : item.queued ? 'Queued' : 'You'}</MessageHeader><Card size="sm"><CardContent className="prose prose-sm max-w-none dark:prose-invert"><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.message.content ?? ''}</ReactMarkdown></CardContent></Card></MessageContent></Message> }

function Machines({ token }: { token: string }) { const peers = useQuery({ queryKey: ['peers'], queryFn: () => api<Peer[]>('/api/peers', token) }); const [name, setName] = useState(''); const [baseUrl, setBaseUrl] = useState(''); const [error, setError] = useState(''); const add = async (event: FormEvent) => { event.preventDefault(); try { await api('/api/peers', token, { method: 'POST', body: JSON.stringify({ name, base_url: baseUrl }) }); setName(''); setBaseUrl(''); await peers.refetch() } catch (cause) { setError(message(cause)) } }; return <Page title="Machines" description="Connect Mobius servers to this operator."><Card><CardHeader><CardTitle>Enrolled machines</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{peers.data?.map((peer) => <div key={peer.id} className="flex items-center gap-3"><ServerIcon /><div className="min-w-0 flex-1"><p className="font-medium">{peer.name}</p><p className="truncate text-sm text-muted-foreground">{peer.base_url}</p></div><Button variant="ghost" size="icon-sm" onClick={async () => { await api(`/api/peers/${peer.id}`, token, { method: 'DELETE' }); await peers.refetch() }}><XIcon /></Button></div>)}{peers.data?.length === 0 && <p className="text-sm text-muted-foreground">No remote machines enrolled.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Add a machine</CardTitle></CardHeader><CardContent><form className="flex flex-col gap-4" onSubmit={add}><FieldGroup><Field><FieldLabel htmlFor="peer-name">Name</FieldLabel><Input id="peer-name" value={name} onChange={(event) => setName(event.target.value)} required /></Field><Field><FieldLabel htmlFor="peer-url">Mobius URL</FieldLabel><Input id="peer-url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field></FieldGroup>{error && <ErrorAlert error={error} />}<Button><PlusIcon data-icon="inline-start" />Add machine</Button></form></CardContent></Card></Page> }

function FilesPage({ token }: { token: string }) { const [path, setPath] = useState('/'); const [selected, setSelected] = useState<FileEntry | null>(null); const [content, setContent] = useState(''); const files = useQuery({ queryKey: ['files', path], queryFn: () => api<FileEntry[]>(`/api/files?path=${encodeURIComponent(path)}`, token) }); const open = async (entry: FileEntry) => { if (entry.kind === 'directory') { setPath(entry.path); return } setSelected(entry); const result = await api<{ content: string }>(`/api/files/read?path=${encodeURIComponent(entry.path)}`, token); setContent(result.content) }; return <Page title="Files" description="Browse and edit the active machine."><Card><CardContent className="pt-4"><InputGroup><Input value={path} onChange={(event) => setPath(event.target.value)} /><InputGroupAddon align="inline-end"><InputGroupButton onClick={() => files.refetch()}><RefreshCwIcon />Refresh</InputGroupButton></InputGroupAddon></InputGroup></CardContent></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Directory</CardTitle></CardHeader><CardContent className="flex flex-col gap-1">{files.data?.map((entry) => <Button key={entry.path} variant="ghost" className="justify-start" onClick={() => open(entry)}>{entry.kind === 'directory' ? <FolderIcon data-icon="inline-start" /> : <FileIcon data-icon="inline-start" />}{entry.name}</Button>)}</CardContent></Card><Card><CardHeader><CardTitle>{selected?.path ?? 'Select a file'}</CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><Textarea value={content} onChange={(event) => setContent(event.target.value)} disabled={!selected} className="min-h-80 font-mono" /><Button disabled={!selected} onClick={() => selected && api('/api/files/write', token, { method: 'PUT', body: JSON.stringify({ path: selected.path, content }) })}>Save</Button></CardContent></Card></div></Page> }

function ResourcesPage({ token }: { token: string }) { const resources = useQuery({ queryKey: ['resources'], queryFn: () => api<any>('/api/system/resources', token), refetchInterval: 5000 }); const cards = resources.data ? [{ label: 'CPU', value: `${resources.data.cpu.usage_percent.toFixed(1)}%`, icon: ActivityIcon }, { label: 'Memory', value: `${bytes(resources.data.memory.used_bytes)} / ${bytes(resources.data.memory.total_bytes)}`, icon: DatabaseIcon }, { label: 'Network', value: `${bytes(resources.data.network.receive_bytes_per_second)}/s`, icon: NetworkIcon }, { label: 'Disk', value: resources.data.disk ? `${bytes(resources.data.disk.used_bytes)} / ${bytes(resources.data.disk.total_bytes)}` : '—', icon: HardDriveIcon }] : []; return <Page title="Resources" description="Live capacity and local database usage."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon }) => <Card key={label}><CardHeader><CardDescription className="flex items-center gap-2"><Icon />{label}</CardDescription><CardTitle>{value}</CardTitle></CardHeader></Card>)}</div></Page> }

function SettingsPage({ token }: { token: string }) { const queryClient = useQueryClient(); const settings = useQuery({ queryKey: ['settings'], queryFn: () => api<Settings>('/api/settings', token) }); const [model, setModel] = useState(''); useEffect(() => { setModel(settings.data?.default_model ?? '') }, [settings.data]); return <Page title="Settings" description="Configure this machine's default agent model."><Card><CardHeader><CardTitle>Default model</CardTitle><CardDescription>Used by the next agent turn.</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-4" onSubmit={async (event) => { event.preventDefault(); const saved = await api<Settings>('/api/settings', token, { method: 'PUT', body: JSON.stringify({ default_model: model }) }); queryClient.setQueryData(['settings'], saved) }}><Field><FieldLabel htmlFor="model">Model ID</FieldLabel><Input id="model" value={model} onChange={(event) => setModel(event.target.value)} required /><FieldDescription>Use a model supported by the configured upstream.</FieldDescription></Field><Button>Save changes</Button></form></CardContent></Card></Page> }

function Page({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <main className="mx-auto flex w-full max-w-6xl flex-col gap-6 p-4 md:p-6"><div><h1 className="font-heading text-2xl font-semibold">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></div>{children}</main> }
function ErrorAlert({ error }: { error: string }) { return <Alert variant="destructive"><AlertTitle>Request failed</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> }

createRoot(document.getElementById('root')!).render(<QueryClientProvider client={queryClient}><TooltipProvider><UiProvider><HashRouter><App /></HashRouter></UiProvider></TooltipProvider></QueryClientProvider>)
