import { QueryClient, QueryClientProvider, useQuery, useQueryClient } from '@tanstack/react-query'
import { createBrowserSdk } from 'auth-mini/sdk/browser'
import type { AuthMiniApi, SessionSnapshot } from 'auth-mini/sdk/browser'
import { ActivityIcon, BotIcon, CheckIcon, CircleStopIcon, CpuIcon, DatabaseIcon, FileIcon, FolderIcon, HardDriveIcon, KeyRoundIcon, LanguagesIcon, MemoryStickIcon, MonitorCogIcon, NetworkIcon, PanelLeftIcon, PlusIcon, RefreshCwIcon, SendIcon, ServerIcon, Settings2Icon, TerminalSquareIcon, XIcon } from 'lucide-react'
import { createContext, FormEvent, ReactNode, useContext, useEffect, useRef, useState } from 'react'
import { HashRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { createRoot } from 'react-dom/client'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { DropdownMenu, DropdownMenuContent, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupTextarea } from '@/components/ui/input-group'
import { Message, MessageAvatar, MessageContent, MessageHeader } from '@/components/ui/message'
import { MessageScroller, MessageScrollerButton, MessageScrollerContent, MessageScrollerItem, MessageScrollerProvider, MessageScrollerViewport } from '@/components/ui/message-scroller'
import { Progress } from '@/components/ui/progress'
import { Separator } from '@/components/ui/separator'
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { Spinner } from '@/components/ui/spinner'
import { Textarea } from '@/components/ui/textarea'
import { TooltipProvider } from '@/components/ui/tooltip'
import './styles.css'

declare global { interface Window { __MOBIUS_AUTH_URL: string | null } }

type Status = { machine_id: string; hostname: string; root_user_id: string; auth_url: string; openai_base_url: string }
type Settings = { default_model: string }
type Peer = { id: string; name: string; base_url: string; created_at: string }
type FileEntry = { name: string; path: string; kind: 'file' | 'directory'; size: number }
type SystemResources = { sampled_at: number; sample_interval_ms: number; cpu: { usage_percent: number; load_1m: number; logical_cpus: number }; memory: { used_bytes: number; total_bytes: number; available_bytes: number; process_used_bytes: number; other_used_bytes: number; usage_percent: number; swap_used_bytes: number; swap_total_bytes: number }; network: { receive_bytes_per_second: number; transmit_bytes_per_second: number; interfaces: number }; disk: { mount_point: string; used_bytes: number; total_bytes: number; available_bytes: number; usage_percent: number } | null; sqlite: { main_bytes: number; wal_bytes: number; shm_bytes: number; total_bytes: number; freelist_bytes: number; freelist_percent: number } }
type ChatMessage = { role: string; content: string | null }
type AgentEvent = { type: 'tool_call'; call_id: string; name: string } | { type: 'tool_result'; call_id: string; name: string } | { type: 'context'; input_tokens: number } | { type: 'complete'; message: ChatMessage } | { type: 'error'; error: string }
type ConversationItem = { kind: 'message'; id: string; message: ChatMessage; queued: boolean } | { kind: 'tool'; call_id: string; name: string; complete: boolean }
type Session = SessionSnapshot
type Language = 'en' | 'zh'

const words = {
  en: {
    machine: 'Machine', console: 'Console', machines: 'Machines', files: 'Files', resources: 'Resources', settings: 'Settings', connecting: 'Connecting…', loadingMachine: 'Loading machine', online: 'Online', light: 'Light', dark: 'Dark', signOut: 'Sign out', language: 'Language',
    consoleDescription: 'Agent activity is streamed as it happens.', context: 'Context', tokens: 'tokens', stop: 'Stop', agentWorking: 'Agent is working…', greeting: 'I am connected to this machine. Tell me the outcome you want to reach.', agent: 'Agent', you: 'You', queued: 'Queued', completed: 'Completed', calling: 'Calling', outcomePlaceholder: 'Describe the outcome you want…', queuedPlaceholder: 'Add a follow-up prompt to the queue…', composeHint: 'Enter to send · Shift+Enter for a new line', queuedCount: 'queued',
    machinesTitle: 'Machines', machinesDescription: 'Connect Mobius servers to this operator.', enrolledMachines: 'Enrolled machines', noMachines: 'No remote machines enrolled.', addMachine: 'Add a machine', name: 'Name', mobiusUrl: 'Mobius URL', add: 'Add machine', remove: 'Remove',
    filesTitle: 'Files', filesDescription: 'Browse and edit the active machine.', refresh: 'Refresh', directory: 'Directory', selectFile: 'Select a file', save: 'Save',
    resourcesTitle: 'Resources', resourcesDescription: 'Live capacity and local database usage.', sampled: 'Sampled', cpu: 'CPU', memory: 'Memory', network: 'Network', disk: 'Disk', sqlite: 'SQLite database', load1m: '1m load', logicalCpus: 'Logical CPUs', processMemory: 'Mobius RSS', otherMemory: 'Other system usage', available: 'Available', swap: 'Swap', received: 'Received', transmitted: 'Transmitted', interfaces: 'Interfaces', mount: 'Mount', main: 'Main', wal: 'WAL', shm: 'SHM', reclaimable: 'Reclaimable', unavailable: 'Unavailable',
    settingsTitle: 'Settings', settingsDescription: 'Configure this machine\'s default agent model.', defaultModel: 'Default model', defaultModelDescription: 'Used by the next agent turn.', modelId: 'Model ID', modelHint: 'Use a model supported by the configured upstream.', saveChanges: 'Save changes',
  },
  zh: {
    machine: '机器', console: '控制台', machines: '机器', files: '文件', resources: '资源', settings: '设置', connecting: '正在连接…', loadingMachine: '正在加载机器', online: '在线', light: '亮色', dark: '深色', signOut: '退出登录', language: '语言',
    consoleDescription: '实时展示 Agent 的执行过程。', context: '上下文', tokens: 'tokens', stop: '停止', agentWorking: 'Agent 正在执行…', greeting: '我已连接到这台机器。请告诉我你想要达成的结果。', agent: 'Agent', you: '你', queued: '排队中', completed: '已完成', calling: '正在调用', outcomePlaceholder: '描述你想要的结果…', queuedPlaceholder: '追加一条后续提示词…', composeHint: 'Enter 发送 · Shift+Enter 换行', queuedCount: '条排队中',
    machinesTitle: '机器', machinesDescription: '将 Mobius 服务器接入当前操作台。', enrolledMachines: '已接入机器', noMachines: '尚未接入远程机器。', addMachine: '添加机器', name: '名称', mobiusUrl: 'Mobius URL', add: '添加机器', remove: '移除',
    filesTitle: '文件', filesDescription: '浏览并编辑当前机器。', refresh: '刷新', directory: '目录', selectFile: '选择文件', save: '保存',
    resourcesTitle: '系统资源', resourcesDescription: '实时容量和本地数据库占用。', sampled: '采样时间', cpu: 'CPU', memory: '内存', network: '网络', disk: '磁盘', sqlite: 'SQLite 数据库', load1m: '1 分钟负载', logicalCpus: '逻辑核心', processMemory: 'Mobius RSS', otherMemory: '其他系统占用', available: '可用', swap: '交换分区', received: '接收', transmitted: '发送', interfaces: '网卡', mount: '挂载点', main: '主文件', wal: 'WAL', shm: 'SHM', reclaimable: '可回收', unavailable: '不可用',
    settingsTitle: '设置', settingsDescription: '配置当前机器默认使用的 Agent 模型。', defaultModel: '默认模型', defaultModelDescription: '用于下一轮 Agent 对话。', modelId: '模型 ID', modelHint: '请输入当前上游支持的模型。', saveChanges: '保存更改',
  },
} as const
type TranslationKey = keyof typeof words.en

const queryClient = new QueryClient()
const UiContext = createContext<{ dark: boolean; toggleTheme: () => void; language: Language; setLanguage: (language: Language) => void; t: (key: TranslationKey) => string } | null>(null)

function UiProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem('mobius.language') === 'zh' ? 'zh' : 'en')
  const [dark, setDark] = useState(() => localStorage.getItem('mobius.theme') === 'dark' || (!localStorage.getItem('mobius.theme') && matchMedia('(prefers-color-scheme: dark)').matches))
  useEffect(() => { document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'; localStorage.setItem('mobius.language', language) }, [language])
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('mobius.theme', dark ? 'dark' : 'light') }, [dark])
  return <UiContext.Provider value={{ dark, toggleTheme: () => setDark((value) => !value), language, setLanguage, t: (key) => words[language][key] }}>{children}</UiContext.Provider>
}

function useUi() { const value = useContext(UiContext); if (!value) throw new Error('UI context is missing'); return value }
function anonymous(): Session { return { status: 'anonymous', authenticated: false, sessionId: null, accessToken: null, refreshToken: null, receivedAt: null, expiresAt: null } }
function useBrowserSession(sdk: AuthMiniApi | null) { const [session, setSession] = useState<Session>(() => sdk?.session.getState() ?? anonymous()); useEffect(() => { if (!sdk) return; setSession(sdk.session.getState()); return sdk.session.onChange(setSession) }, [sdk]); return session }
function message(cause: unknown) { return cause instanceof Error ? cause.message : 'Something went wrong.' }
function bytes(value: number) { const units = ['B', 'KB', 'MB', 'GB', 'TB']; let size = value; let index = 0; while (size >= 1024 && index < units.length - 1) { size /= 1024; index++ } return `${size >= 10 || index === 0 ? size.toFixed(0) : size.toFixed(1)} ${units[index]}` }

async function api<T>(path: string, token: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...init?.headers } })
  if (!response.ok) { const body = await response.json().catch(() => ({ error: response.statusText })); throw new Error(body.error ?? response.statusText) }
  return response.json() as Promise<T>
}

async function streamAgentTurn(token: string, runId: string, messages: ChatMessage[], signal: AbortSignal, onEvent: (event: AgentEvent) => void) {
  const response = await fetch('/api/agent/turn', { method: 'POST', signal, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ run_id: runId, messages }) })
  if (!response.ok) { const body = await response.json().catch(() => ({ error: response.statusText })); throw new Error(body.error ?? response.statusText) }
  const reader = response.body?.getReader(); if (!reader) throw new Error('The agent did not start an event stream.')
  const decoder = new TextDecoder(); let buffer = ''
  for (;;) { const { done, value } = await reader.read(); if (done) return; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop() ?? ''; for (const line of lines) { if (!line.startsWith('data: ')) continue; const event = JSON.parse(line.slice(6)) as AgentEvent; onEvent(event); if (event.type === 'error') throw new Error(event.error) } }
}

function normalizedAuthUrl(authUrl: string) { const url = new URL(authUrl.trim()); url.search = ''; url.hash = ''; url.pathname = url.pathname.endsWith('/') ? url.pathname : `${url.pathname}/`; return url.toString() }
function beginAuthRedirect(authUrl: string) { const normalized = normalizedAuthUrl(authUrl); const state = crypto.randomUUID(); sessionStorage.setItem('mobius.auth_url', normalized); sessionStorage.setItem('mobius.login_state', state); const callback = `${location.origin}${location.pathname}#/auth/callback`; const params = new URLSearchParams({ redirect_uri: callback, state }); if (location.protocol === 'http:' && ['localhost', '127.0.0.1', '[::1]'].includes(location.hostname)) params.set('aud', location.hostname); location.assign(`${normalized}web/#/login?${params.toString()}`) }
function acceptRedirectSession(): string | null { if (!location.hash.startsWith('#/auth/callback?')) return null; const params = new URLSearchParams(location.hash.slice('#/auth/callback?'.length)); const state = sessionStorage.getItem('mobius.login_state'); const authUrl = sessionStorage.getItem('mobius.auth_url'); if (!authUrl || !state || params.get('state') !== state) return null; const accessToken = params.get('access_token'); const sessionId = params.get('session_id'); const refreshToken = params.get('refresh_token'); const expiresIn = Number(params.get('expires_in')); if (!accessToken || !sessionId || !refreshToken || !Number.isFinite(expiresIn)) return null; const receivedAt = new Date(); localStorage.setItem(`auth-mini.sdk:${normalizedAuthUrl(authUrl)}`, JSON.stringify({ accessToken, sessionId, refreshToken, receivedAt: receivedAt.toISOString(), expiresAt: new Date(receivedAt.getTime() + expiresIn * 1000).toISOString() })); sessionStorage.removeItem('mobius.login_state'); history.replaceState(null, '', `${location.pathname}${location.search}#/console`); return authUrl }

function App() { const authUrl = acceptRedirectSession() ?? window.__MOBIUS_AUTH_URL; const [sdk] = useState<AuthMiniApi | null>(() => authUrl ? createBrowserSdk(authUrl) : null); const session = useBrowserSession(sdk); if (!authUrl) return <Bootstrap session={session} />; if (session.status === 'recovering') return <main className="grid min-h-svh place-items-center"><Spinner /></main>; if (!session.accessToken) return <SignIn />; return <Workspace sdk={sdk} token={session.accessToken} /> }

function Bootstrap({ session }: { session: Session }) { const [authUrl, setAuthUrl] = useState(() => sessionStorage.getItem('mobius.auth_url') ?? ''); const [apiKey, setApiKey] = useState(''); const [baseUrl, setBaseUrl] = useState('https://api.openai.com/v1'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const signIn = () => { try { beginAuthRedirect(authUrl) } catch (cause) { setError(message(cause)) } }; const setup = async (event: FormEvent) => { event.preventDefault(); if (!session.accessToken) return; setBusy(true); try { await api('/api/setup', session.accessToken, { method: 'POST', body: JSON.stringify({ auth_url: authUrl, openai_api_key: apiKey, openai_base_url: baseUrl }) }); location.reload() } catch (cause) { setError(message(cause)) } finally { setBusy(false) } }; return <main className="grid min-h-svh place-items-center p-6"><Card className="w-full max-w-lg"><CardHeader><CardTitle>Initialize Mobius</CardTitle><CardDescription>Bind this machine to your Auth Mini identity and OpenAI-compatible upstream.</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-6" onSubmit={setup}><FieldGroup><Field><FieldLabel htmlFor="auth-url">Auth Mini URL</FieldLabel><Input id="auth-url" value={authUrl} onChange={(event) => setAuthUrl(event.target.value)} required /></Field><Button type="button" variant="secondary" onClick={signIn}><KeyRoundIcon data-icon="inline-start" />Continue with Auth Mini</Button><Field><FieldLabel htmlFor="api-key">OpenAI API key</FieldLabel><Input id="api-key" type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} required /></Field><Field><FieldLabel htmlFor="base-url">Base URL</FieldLabel><Input id="base-url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field></FieldGroup>{error && <ErrorAlert error={error} />}<Button disabled={busy || !session.authenticated}>{busy && <Spinner data-icon="inline-start" />}Initialize</Button></form></CardContent></Card></main> }
function SignIn() { const [error, setError] = useState(''); return <main className="grid min-h-svh place-items-center p-6"><Card className="w-full max-w-sm"><CardHeader><CardTitle>Return to the machine</CardTitle><CardDescription>Sign in through the configured Auth Mini server.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{error && <ErrorAlert error={error} />}<Button onClick={() => { try { beginAuthRedirect(window.__MOBIUS_AUTH_URL!) } catch (cause) { setError(message(cause)) } }}>Continue with Auth Mini</Button></CardContent></Card></main> }

function Workspace({ sdk, token }: { sdk: AuthMiniApi | null; token: string }) {
  const navigate = useNavigate()
  const { dark, language, setLanguage, toggleTheme, t } = useUi()
  const status = useQuery({ queryKey: ['status'], queryFn: () => api<Status>('/api/status', token) })
  const nav = [{ to: '/console', label: t('console'), icon: TerminalSquareIcon }, { to: '/machines', label: t('machines'), icon: NetworkIcon }, { to: '/files', label: t('files'), icon: FileIcon }, { to: '/resources', label: t('resources'), icon: ActivityIcon }, { to: '/settings', label: t('settings'), icon: Settings2Icon }]
  return <SidebarProvider><Sidebar><SidebarHeader><div className="flex items-center gap-2 px-2 py-1 font-heading text-lg font-semibold"><TerminalSquareIcon />Mobius</div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>{t('machine')}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{nav.map(({ to, label, icon: Icon }) => <SidebarMenuItem key={to}><SidebarMenuButton asChild tooltip={label}><NavLink to={to} className={({ isActive }) => isActive ? 'font-medium' : ''}><Icon /><span>{label}</span></NavLink></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter><div className="flex items-center gap-2 px-2 text-xs text-muted-foreground"><ServerIcon />{status.data?.hostname ?? t('connecting')}</div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm"><LanguagesIcon /><span className="sr-only">{t('language')}</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuRadioGroup value={language} onValueChange={(value) => setLanguage(value as Language)}><DropdownMenuRadioItem value="zh">中文</DropdownMenuRadioItem><DropdownMenuRadioItem value="en">English</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu><Button variant="ghost" size="sm" onClick={toggleTheme}><MonitorCogIcon data-icon="inline-start" />{dark ? t('light') : t('dark')}</Button><Button variant="ghost" size="sm" onClick={async () => { await sdk?.session.logout(); navigate('/console') }}>{t('signOut')}</Button></SidebarFooter></Sidebar><SidebarInset><header className="flex h-14 items-center gap-3 border-b px-4"><SidebarTrigger><PanelLeftIcon /></SidebarTrigger><Separator orientation="vertical" className="h-4" /><div className="min-w-0"><p className="truncate text-sm font-medium">{status.data?.hostname ?? t('loadingMachine')}</p></div><Badge className="ml-auto" variant="secondary">{t('online')}</Badge></header><Routes><Route path="/console" element={<Console token={token} />} /><Route path="/machines" element={<Machines token={token} />} /><Route path="/files" element={<FilesPage token={token} />} /><Route path="/resources" element={<ResourcesPage token={token} />} /><Route path="/settings" element={<SettingsPage token={token} />} /><Route path="*" element={<Navigate to="/console" replace />} /></Routes></SidebarInset></SidebarProvider>
}

function Console({ token }: { token: string }) {
  const { t } = useUi()
  const initial = { kind: 'message', id: crypto.randomUUID(), message: { role: 'assistant', content: t('greeting') }, queued: false } as ConversationItem
  const [conversation, setConversation] = useState<ConversationItem[]>([initial]); const conversationRef = useRef(conversation); const queueRef = useRef<{ id: string; message: ChatMessage }[]>([]); const activeRef = useRef<{ id: string; controller: AbortController } | null>(null)
  const [draft, setDraft] = useState(''); const [activeRun, setActiveRun] = useState<string | null>(null); const [contextTokens, setContextTokens] = useState<number | null>(null); const [error, setError] = useState('')
  const updateConversation = (next: ConversationItem[]) => { conversationRef.current = next; setConversation(next) }
  const drain = async (): Promise<void> => { if (activeRef.current || queueRef.current.length === 0) return; const next = queueRef.current.shift()!; updateConversation(conversationRef.current.map((item) => item.kind === 'message' && item.id === next.id ? { ...item, queued: false } : item)); const runId = crypto.randomUUID(); const controller = new AbortController(); activeRef.current = { id: runId, controller }; setActiveRun(runId); setError(''); const messages = conversationRef.current.filter((item): item is Extract<ConversationItem, { kind: 'message' }> => item.kind === 'message' && !item.queued).map((item) => item.message); try { await streamAgentTurn(token, runId, messages, controller.signal, (event) => { if (event.type === 'tool_call') updateConversation([...conversationRef.current, { kind: 'tool', call_id: event.call_id, name: event.name, complete: false }]); if (event.type === 'tool_result') updateConversation(conversationRef.current.map((item) => item.kind === 'tool' && item.call_id === event.call_id ? { ...item, complete: true } : item)); if (event.type === 'context') setContextTokens(event.input_tokens); if (event.type === 'complete') updateConversation([...conversationRef.current, { kind: 'message', id: crypto.randomUUID(), message: event.message, queued: false }]) }) } catch (cause) { if (!controller.signal.aborted) setError(message(cause)) } finally { activeRef.current = null; setActiveRun(null); void drain() } }
  const submit = (event: FormEvent) => { event.preventDefault(); const content = draft.trim(); if (!content) return; const queued = activeRef.current !== null || queueRef.current.length > 0; const entry: Extract<ConversationItem, { kind: 'message' }> = { kind: 'message', id: crypto.randomUUID(), message: { role: 'user', content }, queued }; updateConversation([...conversationRef.current, entry]); queueRef.current.push({ id: entry.id, message: entry.message }); setDraft(''); void drain() }
  const stop = async () => { const active = activeRef.current; if (!active) return; queueRef.current = []; updateConversation(conversationRef.current.filter((item) => item.kind !== 'message' || !item.queued)); active.controller.abort(); await api(`/api/agent/turn/${active.id}`, token, { method: 'DELETE' }).catch(() => undefined) }
  return <main className="flex h-[calc(100svh-3.5rem)] flex-col"><div className="flex flex-wrap items-center gap-2 border-b px-4 py-3"><div><h1 className="font-heading text-lg font-semibold">{t('console')}</h1><p className="text-sm text-muted-foreground">{t('consoleDescription')}</p></div><Badge className="ml-auto" variant="outline">{t('context')}: {contextTokens?.toLocaleString() ?? '—'} {t('tokens')}</Badge>{activeRun && <Button variant="destructive" size="sm" onClick={stop}><CircleStopIcon data-icon="inline-start" />{t('stop')}</Button>}</div><MessageScrollerProvider><MessageScroller className="flex-1"><MessageScrollerViewport><MessageScrollerContent className="mx-auto w-full max-w-4xl p-4">{conversation.map((item) => <MessageScrollerItem key={item.kind === 'tool' ? item.call_id : item.id} scrollAnchor><ConversationEntry item={item} /></MessageScrollerItem>)}{activeRun && <MessageScrollerItem scrollAnchor><div className="flex items-center gap-2 text-sm text-muted-foreground"><Spinner />{t('agentWorking')}</div></MessageScrollerItem>}</MessageScrollerContent></MessageScrollerViewport><MessageScrollerButton /></MessageScroller></MessageScrollerProvider>{error && <div className="px-4 pb-2"><ErrorAlert error={error} /></div>}<form className="border-t p-4" onSubmit={submit}><InputGroup className="mx-auto max-w-4xl"><InputGroupTextarea value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit() } }} placeholder={activeRun ? t('queuedPlaceholder') : t('outcomePlaceholder')} rows={2} /><InputGroupAddon align="inline-end"><InputGroupButton type="submit" variant="default" size="icon-sm"><SendIcon /><span className="sr-only">{t('console')}</span></InputGroupButton></InputGroupAddon></InputGroup><p className="mx-auto mt-2 max-w-4xl text-xs text-muted-foreground">{t('composeHint')}{queueRef.current.length > 0 ? ` · ${queueRef.current.length} ${t('queuedCount')}` : ''}</p></form></main>
}

function ConversationEntry({ item }: { item: ConversationItem }) { const { t } = useUi(); if (item.kind === 'tool') return <div className="flex items-center gap-2"><Badge variant={item.complete ? 'secondary' : 'outline'}>{item.complete ? <CheckIcon data-icon="inline-start" /> : <Spinner data-icon="inline-start" />}{item.complete ? t('completed') : t('calling')} {item.name}</Badge></div>; const assistant = item.message.role === 'assistant'; return <Message align={assistant ? 'start' : 'end'}><MessageAvatar>{assistant ? <BotIcon /> : t('you')}</MessageAvatar><MessageContent><MessageHeader>{assistant ? t('agent') : item.queued ? t('queued') : t('you')}</MessageHeader><Card size="sm"><CardContent className="prose prose-sm max-w-none dark:prose-invert"><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.message.content ?? ''}</ReactMarkdown></CardContent></Card></MessageContent></Message> }

function Machines({ token }: { token: string }) { const peers = useQuery({ queryKey: ['peers'], queryFn: () => api<Peer[]>('/api/peers', token) }); const [name, setName] = useState(''); const [baseUrl, setBaseUrl] = useState(''); const [error, setError] = useState(''); const add = async (event: FormEvent) => { event.preventDefault(); try { await api('/api/peers', token, { method: 'POST', body: JSON.stringify({ name, base_url: baseUrl }) }); setName(''); setBaseUrl(''); await peers.refetch() } catch (cause) { setError(message(cause)) } }; return <Page title="Machines" description="Connect Mobius servers to this operator."><Card><CardHeader><CardTitle>Enrolled machines</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{peers.data?.map((peer) => <div key={peer.id} className="flex items-center gap-3"><ServerIcon /><div className="min-w-0 flex-1"><p className="font-medium">{peer.name}</p><p className="truncate text-sm text-muted-foreground">{peer.base_url}</p></div><Button variant="ghost" size="icon-sm" onClick={async () => { await api(`/api/peers/${peer.id}`, token, { method: 'DELETE' }); await peers.refetch() }}><XIcon /></Button></div>)}{peers.data?.length === 0 && <p className="text-sm text-muted-foreground">No remote machines enrolled.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Add a machine</CardTitle></CardHeader><CardContent><form className="flex flex-col gap-4" onSubmit={add}><FieldGroup><Field><FieldLabel htmlFor="peer-name">Name</FieldLabel><Input id="peer-name" value={name} onChange={(event) => setName(event.target.value)} required /></Field><Field><FieldLabel htmlFor="peer-url">Mobius URL</FieldLabel><Input id="peer-url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} required /></Field></FieldGroup>{error && <ErrorAlert error={error} />}<Button><PlusIcon data-icon="inline-start" />Add machine</Button></form></CardContent></Card></Page> }

function FilesPage({ token }: { token: string }) { const [path, setPath] = useState('/'); const [selected, setSelected] = useState<FileEntry | null>(null); const [content, setContent] = useState(''); const files = useQuery({ queryKey: ['files', path], queryFn: () => api<FileEntry[]>(`/api/files?path=${encodeURIComponent(path)}`, token) }); const open = async (entry: FileEntry) => { if (entry.kind === 'directory') { setPath(entry.path); return } setSelected(entry); const result = await api<{ content: string }>(`/api/files/read?path=${encodeURIComponent(entry.path)}`, token); setContent(result.content) }; return <Page title="Files" description="Browse and edit the active machine."><Card><CardContent className="pt-4"><InputGroup><Input value={path} onChange={(event) => setPath(event.target.value)} /><InputGroupAddon align="inline-end"><InputGroupButton onClick={() => files.refetch()}><RefreshCwIcon />Refresh</InputGroupButton></InputGroupAddon></InputGroup></CardContent></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Directory</CardTitle></CardHeader><CardContent className="flex flex-col gap-1">{files.data?.map((entry) => <Button key={entry.path} variant="ghost" className="justify-start" onClick={() => open(entry)}>{entry.kind === 'directory' ? <FolderIcon data-icon="inline-start" /> : <FileIcon data-icon="inline-start" />}{entry.name}</Button>)}</CardContent></Card><Card><CardHeader><CardTitle>{selected?.path ?? 'Select a file'}</CardTitle></CardHeader><CardContent className="flex flex-col gap-3"><Textarea value={content} onChange={(event) => setContent(event.target.value)} disabled={!selected} className="min-h-80 font-mono" /><Button disabled={!selected} onClick={() => selected && api('/api/files/write', token, { method: 'PUT', body: JSON.stringify({ path: selected.path, content }) })}>Save</Button></CardContent></Card></div></Page> }

function ResourcesPage({ token }: { token: string }) {
  const { language, t } = useUi()
  const resources = useQuery({ queryKey: ['resources'], queryFn: () => api<SystemResources>('/api/system/resources', token), refetchInterval: 5000 })
  if (resources.error) return <Page title={t('resourcesTitle')} description={t('resourcesDescription')}><ErrorAlert error={message(resources.error)} /></Page>
  if (!resources.data) return <Page title={t('resourcesTitle')} description={t('resourcesDescription')}><Card><CardContent className="flex items-center gap-2 pt-6"><Spinner />{t('loadingMachine')}</CardContent></Card></Page>
  const data = resources.data
  const percent = (value: number) => `${value.toFixed(1)}%`
  const sampledAt = new Intl.DateTimeFormat(language === 'zh' ? 'zh-CN' : 'en', { dateStyle: 'short', timeStyle: 'medium' }).format(new Date(data.sampled_at * 1000))
  const metrics = [
    { label: t('cpu'), icon: CpuIcon, value: percent(data.cpu.usage_percent), detail: `${t('load1m')}: ${data.cpu.load_1m.toFixed(2)} · ${t('logicalCpus')}: ${data.cpu.logical_cpus}`, percent: data.cpu.usage_percent },
    { label: t('memory'), icon: MemoryStickIcon, value: `${bytes(data.memory.used_bytes)} / ${bytes(data.memory.total_bytes)}`, detail: `${t('processMemory')}: ${bytes(data.memory.process_used_bytes)} · ${t('otherMemory')}: ${bytes(data.memory.other_used_bytes)} · ${t('available')}: ${bytes(data.memory.available_bytes)}`, secondary: `${t('swap')}: ${bytes(data.memory.swap_used_bytes)} / ${bytes(data.memory.swap_total_bytes)}`, percent: data.memory.usage_percent },
    { label: t('network'), icon: NetworkIcon, value: `${t('received')}: ${bytes(data.network.receive_bytes_per_second)}/s · ${t('transmitted')}: ${bytes(data.network.transmit_bytes_per_second)}/s`, detail: `${t('interfaces')}: ${data.network.interfaces}` },
    { label: t('disk'), icon: HardDriveIcon, value: data.disk ? `${bytes(data.disk.used_bytes)} / ${bytes(data.disk.total_bytes)}` : '—', detail: data.disk ? `${t('available')}: ${bytes(data.disk.available_bytes)} · ${t('mount')}: ${data.disk.mount_point}` : t('unavailable'), percent: data.disk?.usage_percent },
    { label: t('sqlite'), icon: DatabaseIcon, value: bytes(data.sqlite.total_bytes), detail: `${t('main')}: ${bytes(data.sqlite.main_bytes)} · ${t('wal')}: ${bytes(data.sqlite.wal_bytes)} · ${t('shm')}: ${bytes(data.sqlite.shm_bytes)}`, secondary: `${t('reclaimable')}: ${bytes(data.sqlite.freelist_bytes)} · ${percent(data.sqlite.freelist_percent)}`, percent: data.sqlite.freelist_percent },
  ]
  return <Page title={t('resourcesTitle')} description={t('resourcesDescription')}><Card><CardHeader><CardTitle>{t('resourcesTitle')}</CardTitle><CardDescription>{t('resourcesDescription')}</CardDescription><Badge className="mt-2 w-fit" variant="outline">{t('sampled')}: {sampledAt} · 5s</Badge></CardHeader><CardContent><dl className="overflow-hidden rounded-lg border"><div className="flex flex-col gap-4 p-4">{metrics.map(({ label, icon: Icon, value, detail, secondary, percent: usagePercent }) => <div key={label} className="grid gap-3 md:grid-cols-[minmax(9rem,0.75fr)_minmax(14rem,1fr)_minmax(16rem,1.5fr)] md:items-center"><dt className="flex items-center gap-2 font-medium"><Icon />{label}</dt><dd className="font-medium tabular-nums">{value}</dd><dd className="flex min-w-0 flex-col gap-2 text-xs text-muted-foreground"><span className="truncate" title={detail}>{detail}</span>{secondary && <span className="truncate font-medium text-foreground" title={secondary}>{secondary}</span>}{usagePercent !== undefined && <Progress aria-label={`${label}: ${percent(usagePercent)}`} value={Math.max(0, Math.min(100, usagePercent))} />}</dd></div>)}</div></dl></CardContent></Card></Page>
}

function SettingsPage({ token }: { token: string }) { const queryClient = useQueryClient(); const settings = useQuery({ queryKey: ['settings'], queryFn: () => api<Settings>('/api/settings', token) }); const [model, setModel] = useState(''); useEffect(() => { setModel(settings.data?.default_model ?? '') }, [settings.data]); return <Page title="Settings" description="Configure this machine's default agent model."><Card><CardHeader><CardTitle>Default model</CardTitle><CardDescription>Used by the next agent turn.</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-4" onSubmit={async (event) => { event.preventDefault(); const saved = await api<Settings>('/api/settings', token, { method: 'PUT', body: JSON.stringify({ default_model: model }) }); queryClient.setQueryData(['settings'], saved) }}><Field><FieldLabel htmlFor="model">Model ID</FieldLabel><Input id="model" value={model} onChange={(event) => setModel(event.target.value)} required /><FieldDescription>Use a model supported by the configured upstream.</FieldDescription></Field><Button>Save changes</Button></form></CardContent></Card></Page> }

function Page({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <main className="mx-auto flex w-full max-w-6xl flex-col gap-6 p-4 md:p-6"><div><h1 className="font-heading text-2xl font-semibold">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></div>{children}</main> }
function ErrorAlert({ error }: { error: string }) { return <Alert variant="destructive"><AlertTitle>Request failed</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> }

createRoot(document.getElementById('root')!).render(<QueryClientProvider client={queryClient}><TooltipProvider><UiProvider><HashRouter><App /></HashRouter></UiProvider></TooltipProvider></QueryClientProvider>)
